/**
* Authors: Hayden Tran (102882815), Rhyanna Arisya Zaharom (103698709)
* Target: index.html
* Created: 29th April 2023
**/

function init() {

    // Define the SVG width and height
    var width = 800;
    var height = 600;

    // Create the SVG element and set its dimensions
    var svg1 = d3.select("#chart1")
      .append("svg")
      .attr("width", width)
      .attr("height", height);

    // Load the GeoJSON file containing the map data of Somalia
    d3.json("somalia_with_regions.json").then(function(data) {
      // Create a projection of the GeoJSON data onto the SVG element
      var projection = d3.geoMercator()
        .center([48.5, 5.5])
        .scale(2300)
        .translate([width / 2, height / 2]);

      // Create a path for the projected GeoJSON data
      var path = d3.geoPath().projection(projection);

      // Append a path element to the SVG element and set its "d" attribute to the path generated by the D3.geoPath() method
      svg1.append("path")
        .datum(data)
        .attr("d", path)
        .attr("fill", "#A3CACC")
        .attr("stroke", "#373E40")
        .attr("stroke-width", 0.5);
    });


  var svg = d3.select("#chart2")
      .append("svg")
      .attr("width", w)
      .attr("height", h);

  var svg = d3.select("#chart3")
      .append("svg")
      .attr("width", w)
      .attr("height", h);
}

window.onload = init;
